server:
  session-timeout: 60
  port: 8089
mybatis:
  mapper-locations: classpath:com/geovis/mapper/xml/*.xml
  type-aliases-package: com.geovis.entity
logging:
  path: d:/logs
  config: classpath:logback-spring.xml
mysql:
  datasource:
    read01:
      minIdle: 5
      validationQuery: select 'x'
      initialSize: 10
      maxWait: 60000
      poolPreparedStatements: true
      filters: stat
      url: jdbc:mysql://172.20.10.14:3306/shiro?useUnicode=true&characterEncoding=utf-8
      maxPoolPreparedStatementPerConnectionSize: 50
      password: root
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testOnReturn: false
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 100
      username: root
    mapperLocations: classpath:/com/geovis/mapper/xml/*.xml
    type: com.alibaba.druid.pool.DruidDataSource
    configLocation: classpath:/mybatis-config.xml
    write:
      minIdle: 5
      validationQuery: select 'x'
      initialSize: 10
      maxWait: 60000
      poolPreparedStatements: true
      filters: stat
      url: jdbc:mysql://172.20.10.2:3306/shiro?useUnicode=true&characterEncoding=utf-8
      maxPoolPreparedStatementPerConnectionSize: 50
      password: root
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 100
      username: root
    readSize: 2
redis:
     hostName: localhost
     #password:
     port: 6379
     timeout: 10000
     maxWaitMillis: 1000
     testOnBorrow: true
     testWhileIdle: true
     maxIdle: 300
     minEvictableIdleTimeMillis: 300000
     timeBetweenEvictionRunsMillis: 30000
     maxTotal: 1000
     numTestsPerEvictionRun: 1024
     #哨兵模式根据名称自动选择master
     sentinel:
        master: mymaster
        nodes: 192.168.2.183:7000,192.168.2.183:7001,192.168.2.183:7002
cluster:
      nodes: 192.168.2.183:7000,192.168.2.183:7001,192.168.2.183:7002,192.168.2.183:7003,192.168.2.183:7004,192.168.2.183:7005
      max-redirects: 3
data:
      mongodb:
          uri: mongodb://admin:admin@127.0.0.1:27017,127.0.0.1:27017,127.0.0.1:27017
          database: PcWeb

mapper-locations: classpath:com/geovis/mapper/xml/*.xml
mybatis:type-aliases-package: com.geovis.entity
